# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ainWindow(object):
    def setupUi(self, ainWindow):
        ainWindow.setObjectName("ainWindow")
        ainWindow.resize(1500, 1000)
        ainWindow.setStyleSheet("background-color: rgb(15, 40, 52);")
        self.centralwidget = QtWidgets.QWidget(ainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graph_one_channaks = QtWidgets.QWidget(self.centralwidget)
        self.graph_one_channaks.setGeometry(QtCore.QRect(20, 120, 301, 321))
        self.graph_one_channaks.setStyleSheet("QWidget {\n"
"    background-color: #183747; /* Background color */\n"
"    border-radius: 15px; /* Curved borders */\n"
"    border: 2px solid #2d2d2d; /* 3D outline */\n"
"    min-width: 100px; /* Ensures it\'s square */\n"
"    min-height: 100px; /* Ensures it\'s square */\n"
"    box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.7); /* 3D shadow effect */\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.graph_one_channaks.setObjectName("graph_one_channaks")
        self.graph_two_channals = QtWidgets.QWidget(self.centralwidget)
        self.graph_two_channals.setGeometry(QtCore.QRect(20, 520, 311, 381))
        self.graph_two_channals.setStyleSheet("QWidget {\n"
"    background-color: #183747; /* Background color */\n"
"    border-radius: 15px; /* Curved borders */\n"
"    border: 2px solid #2d2d2d; /* 3D outline */\n"
"    min-width: 100px; /* Ensures it\'s square */\n"
"    min-height: 100px; /* Ensures it\'s square */\n"
"    box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.7); /* 3D shadow effect */\n"
"}")
        self.graph_two_channals.setObjectName("graph_two_channals")
        self.tools = QtWidgets.QWidget(self.centralwidget)
        self.tools.setGeometry(QtCore.QRect(1270, -10, 221, 981))
        self.tools.setObjectName("tools")
        self.frame = QtWidgets.QFrame(self.tools)
        self.frame.setGeometry(QtCore.QRect(10, 40, 201, 20))
        self.frame.setStyleSheet("gridline-color: rgb(255, 85, 0);\n"
"selection-color: rgb(255, 85, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.tools)
        self.pushButton.setGeometry(QtCore.QRect(40, 210, 151, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #FFC300;    /* Yellow color */\n"
"    border-radius: 10px;          /* Rounded corners (10px as in the image) */\n"
"    border: none;                 /* No border */\n"
"    color: white;                 /* Text color */\n"
"    padding: 5px;                 /* Padding for better text alignment */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD54F;    /* Lighter yellow when hovering */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFA000;    /* Darker yellow when pressed */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tools)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 280, 151, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #FFC300;    /* Yellow color */\n"
"    border-radius: 10px;          /* Rounded corners (10px as in the image) */\n"
"    border: none;                 /* No border */\n"
"    color: white;                 /* Text color */\n"
"    padding: 5px;                 /* Padding for better text alignment */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD54F;    /* Lighter yellow when hovering */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFA000;    /* Darker yellow when pressed */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.tools)
        self.comboBox.setGeometry(QtCore.QRect(60, -20, 121, 51))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.checkBox = QtWidgets.QCheckBox(self.tools)
        self.checkBox.setGeometry(QtCore.QRect(70, 70, 101, 41))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.pushButton_5 = QtWidgets.QPushButton(self.tools)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 350, 151, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #FFC300;    /* Yellow color */\n"
"    border-radius: 10px;          /* Rounded corners (10px as in the image) */\n"
"    border: none;                 /* No border */\n"
"    color: white;                 /* Text color */\n"
"    padding: 5px;                 /* Padding for better text alignment */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD54F;    /* Lighter yellow when hovering */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFA000;    /* Darker yellow when pressed */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tools)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 420, 151, 41))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #FFC300;    /* Yellow color */\n"
"    border-radius: 10px;          /* Rounded corners (10px as in the image) */\n"
"    border: none;                 /* No border */\n"
"    color: white;                 /* Text color */\n"
"    padding: 5px;                 /* Padding for better text alignment */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD54F;    /* Lighter yellow when hovering */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFA000;    /* Darker yellow when pressed */\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalSlider = QtWidgets.QSlider(self.tools)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 510, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tools)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(40, 560, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.color_push_button = QtWidgets.QPushButton(self.tools)
        self.color_push_button.setGeometry(QtCore.QRect(40, 150, 151, 41))
        self.color_push_button.setStyleSheet("QPushButton {\n"
"    background-color: #FFC300;    /* Yellow color */\n"
"    border-radius: 10px;          /* Rounded corners (10px as in the image) */\n"
"    border: none;                 /* No border */\n"
"    color: white;                 /* Text color */\n"
"    padding: 5px;                 /* Padding for better text alignment */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD54F;    /* Lighter yellow when hovering */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFA000;    /* Darker yellow when pressed */\n"
"}\n"
"")
        self.color_push_button.setObjectName("color_push_button")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(350, 470, 911, 20))
        self.frame_3.setStyleSheet("gridline-color: rgb(255, 85, 0);\n"
"selection-color: rgb(255, 85, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setMidLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 50, 261, 41))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #FFC300;    /* Yellow color */\n"
"    border-radius: 10px;          /* Rounded corners (10px as in the image) */\n"
"    border: none;                 /* No border */\n"
"    color: white;                 /* Text color */\n"
"    padding: 5px;                 /* Padding for better text alignment */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD54F;    /* Lighter yellow when hovering */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFA000;    /* Darker yellow when pressed */\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.Graph1_widget = QtWidgets.QWidget(self.centralwidget)
        self.Graph1_widget.setGeometry(QtCore.QRect(340, 0, 921, 461))
        self.Graph1_widget.setStyleSheet("QWidget {\n"
"    background-color: #183747; /* Background color */\n"
"    border-radius: 15px; /* Curved borders */\n"
"    border: 2px solid #2d2d2d; /* 3D outline */\n"
"    min-width: 100px; /* Ensures it\'s square */\n"
"    min-height: 100px; /* Ensures it\'s square */\n"
"    box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.7); /* 3D shadow effect */\n"
"}")
        self.Graph1_widget.setObjectName("Graph1_widget")
        self.Graph1_widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.Graph1_widget_2.setGeometry(QtCore.QRect(340, 490, 921, 471))
        self.Graph1_widget_2.setStyleSheet("QWidget {\n"
"    background-color: #183747; /* Background color */\n"
"    border-radius: 15px; /* Curved borders */\n"
"    border: 2px solid #2d2d2d; /* 3D outline */\n"
"    min-width: 100px; /* Ensures it\'s square */\n"
"    min-height: 100px; /* Ensures it\'s square */\n"
"    box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.7); /* 3D shadow effect */\n"
"}")
        self.Graph1_widget_2.setObjectName("Graph1_widget_2")
        ainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 26))
        self.menubar.setObjectName("menubar")
        ainWindow.setMenuBar(self.menubar)

        self.retranslateUi(ainWindow)
        QtCore.QMetaObject.connectSlotsByName(ainWindow)

    def retranslateUi(self, ainWindow):
        _translate = QtCore.QCoreApplication.translate
        ainWindow.setWindowTitle(_translate("ainWindow", "MainWindow"))
        self.pushButton.setText(_translate("ainWindow", "Pause "))
        self.pushButton_2.setText(_translate("ainWindow", "zoom in"))
        self.checkBox.setText(_translate("ainWindow", "Linked"))
        self.pushButton_5.setText(_translate("ainWindow", "zoom out"))
        self.pushButton_6.setText(_translate("ainWindow", "rewind"))
        self.color_push_button.setText(_translate("ainWindow", "Color"))
        self.pushButton_8.setText(_translate("ainWindow", "Upload File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ainWindow = QtWidgets.QMainWindow()
    ui = Ui_ainWindow()
    ui.setupUi(ainWindow)
    ainWindow.show()
    sys.exit(app.exec_())
